### ISSUE TITLE
support private registry

### ISSUE THREAD

**Issue by mdreizin** [alexanderGugel/ied#104]
It would be nice to pass `auth` headers to support private registry:

```
ied install -r https://user:password@myregistry.npmjs.org
```

Currently I get:

```js
throw new Error('Basic authentication must be done with auth option');
```

**Comment by alexanderGugel** [comment]
In order to define a custom registry, you can use the `--registry` flag or the `IED_REGISTRY` environment variable. This can also be used in order to identify using basic auth.

Alternatively you can set a [bearer token](https://github.com/alexanderGugel/ied/blob/master/src/config.js#L86) via `IED_GLOBAL_NODE_MODULES` environment variable.

This should probably be better documented. Sorry about that.

**Comment by mdreizin** [comment]
@alexanderGugel Thanks a lot for the response ;)

**Comment by alexanderGugel** [comment]
Yeah, sorry for the delay.
