### ISSUE TITLE
Missing support for private / non-npm dependencies

### ISSUE THREAD

**Issue by gka** [alexanderGugel/ied#7]
ied fails when I try to install private dependencies

```
$ ied install
/usr/local/lib/node_modules/ied/lib/install_cmd.js:63
        if (err) throw err
                       ^ 
Error: Unexpected status code 404 for http://registry.npmjs.org/my-private-repo
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/ied/lib/resolve.js:37:17)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

If I run `npm install` everything works fine. The expected behavior is that `ied` uses my ssh keys to load the private repos from github. see [using git urls as dependencies](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by JohnyDays** [comment]
Also run into this, I use a mix of in-house and public packages, and this is currently blocking for me to change :sob:

**Comment by frnk94** [comment]
+1 support for private repo would be great

**Comment by Santinell** [comment]
+1 for git dependencies. Sometimes is needed using forks, like here:
"passport-bitbucket-oauth2": "git+https://github.com/Santinell/passport-bitbucket-oauth2.git"

**Comment by alexanderGugel** [comment]
The current roadmap is something like that:

- [ ] support for private modules
- [ ] support for installing arbitrary tarballs
- [ ] support for git repos

git repos come last, because GitHub at least already gives you tarballs anyways, which you can use in order to work around that feature (but it still means we need it).

**Comment by alexanderGugel** [comment]
As in ec1cdb4a6145686e503aae8a499e4719941effda, scoped **public** packages are now supported. Tested with [@zeke/pubbles](https://www.npmjs.com/package/@zeke/pubbles).

Private npm modules aren't supported yet due to the missing authentication logic that still needs to be added. I expect private packages to be implemented by Thursday or Friday this week.

Stay tuned everyone, we're getting there!

**Comment by avetisk** [comment]
Any update on this?

**Comment by timoxley** [comment]
> git repos come last, because GitHub at least already gives you tarballs anyways

note that git repos are far more popular than any of the other options, perhaps they should go first.

**Comment by alexanderGugel** [comment]
@avetisk No update yet, sorry for the delayed reply. I hope I'm gonna have some time this weekend to finish this.

**Comment by terinjokes** [comment]
@alexanderGugel "GitHub at least already gives you tarballs anyways" except I can't control the dependencies of dependencies.

**Comment by tipiirai** [comment]
Just ran my first `ied install`. *great* experience. Fast indeed. Thank you for the tool. 

I'm also in a need for private repositories.

**Comment by gajus** [comment]
@alexanderGugel 

> Private npm modules aren't supported yet due to the missing authentication logic that still needs to be added. I expect private packages to be implemented by Thursday or Friday this week.
> 
> Stay tuned everyone, we're getting there!

Has this been done?

**Comment by gajus** [comment]
Until this is solved, is it possible to use ied to install all public dependencies and npm for private?

**Comment by duncanfinney** [comment]
@gajus, Thought about doing this with a postinstall. Didn't seem to work quite right for me w/ webpack.

**Comment by mateodelnorte** [comment]
:+1: on github dependencies. 4 of the last places I work, included where I currently work, use github and tags as a form of private npm.

**Comment by paradite** [comment]
I hope it has support for github or git repos soon!

**Comment by cellvia** [comment]
+1

**Comment by benmonro** [comment]
+1, no private repos is a show stopper for us.

**Comment by alexanderGugel** [comment]
Closing for now, since uou can just set the `IED_BEARER_TOKEN` to your npm token.

In order to get your npm token, check your `~/.npmrc` file.

**Source**: https://github.com/alexanderGugel/ied/blob/master/src/config.js#L94

(I'm currently putting together more comprehensive docs (as in "any" docs))

**Comment by timoxley** [comment]
@alexanderGugel this will allow git/tarball dependencies?

**Comment by alexanderGugel** [comment]
Sorry for the delayed response.

Git and tarball dependencies are already supported thanks to @mgcrea
