### ISSUE TITLE
Shared CAS

### ISSUE THREAD

**Issue by rstacruz** [alexanderGugel/ied#72]
This seems like it will eventually be possible: instead of symlinking `node_modules/03abd30a...` into `node_modules/lodash`, you can symlink it from `~/.ied/modules/`. If you include the node version in the hash computation for compiled modules (those that have `node.gyp`), it'd even be cross-compatible even with multiple node versions installed in your system.

**Comment by alexanderGugel** [comment]
Was thinking of this, but the issue is that updating transitive dependencies in one repo might break a completely separate project that has the **same** direct dependency.

Maybe it's worth it, idk. node_modules consume a ton a disk space for no good reason. Sharing them might be a good compromise, but shrinkwraping (which we need in the future) might add a ton of complexity.

I'm open to further discussions about this.
